# Generated by Django 3.2.5 on 2022-01-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dl2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('cache_dir', models.CharField(max_length=200)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl2.user')),
            ],
        ),
    ]
