# Generated by Django 3.2.5 on 2022-01-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dl2', '0001_initial'),
        ('runner', '0001_initial'),
        ('tdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdb',
            name='TestRunner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.testrunner'),
        ),
        migrations.AddField(
            model_name='tdb',
            name='TrainRunner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.trainrunner'),
        ),
        migrations.AlterField(
            model_name='tdb',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dl2.user'),
        ),
    ]
